In [1]:
import numpy as np

In [2]:
import numpy.linalg as lin

## 다음의 데이터를 사용하시오
2 3 5 6 7 10

## a) 데이터 벡터 x를 만드시오

In [3]:
x = np.array([[2,3,5,6,7,10]])

In [4]:
x

array([[ 2,  3,  5,  6,  7, 10]])

## b) 각 데이터의 제곱으로 구성된 벡터 x2를 만드시오

In [5]:
x2= x**2

In [6]:
x2

array([[  4,   9,  25,  36,  49, 100]], dtype=int32)

## c) 각 데이터의 제곱의 합을 구하시오

In [7]:
x2+x2

array([[  8,  18,  50,  72,  98, 200]], dtype=int32)

## d) 각 데이터에서 2를 뺀 값을 구하시오

In [8]:
x-2

array([[0, 1, 3, 4, 5, 8]])

## e) 최대값과 최소값을 구하시오

In [9]:
np.max(x)

10

In [10]:
np.min(x)

2

## f) 5보다 큰 값들로만 구성된 데이터 벡터 x_up을 만드시오

In [11]:
x_up=x[x>5]

In [12]:
x_up

array([ 6,  7, 10])

## g) 벡터 x의 길이를 구하시오

In [13]:
len(x[x>0])

6

## h) x'x를 구하시오 (x'는 x의 전치)

In [14]:
np.dot(x.T,x)

array([[  4,   6,  10,  12,  14,  20],
       [  6,   9,  15,  18,  21,  30],
       [ 10,  15,  25,  30,  35,  50],
       [ 12,  18,  30,  36,  42,  60],
       [ 14,  21,  35,  42,  49,  70],
       [ 20,  30,  50,  60,  70, 100]])

## i) xx'를 구하시오

In [15]:
np.dot(x,x.T)

array([[223]])

## j) 벡터 x와 x2를 열결합(column bind)하여 xc에 저장하시오

In [16]:
xc= np.c_[x,x2]

In [17]:
xc

array([[  2,   3,   5,   6,   7,  10,   4,   9,  25,  36,  49, 100]])

## k) 벡터 x와 x2를 행결합(row bind) 하여 xr에 저장하시오

In [18]:
xr=np.r_[x,x2]

In [19]:
xr

array([[  2,   3,   5,   6,   7,  10],
       [  4,   9,  25,  36,  49, 100]])

# ndarray 다루기

## a) 표준정규분포를 따르는 난수 100개를 가진 배열 x를 만드시오

In [20]:
x=np.array(np.random.randn(100))

In [21]:
x

array([ 0.98130294, -1.07069228, -0.12252941,  0.97430864,  0.41721863,
        0.5215632 ,  1.35180415, -0.87374869,  0.57283013, -0.93308351,
        1.87046792,  1.7484412 ,  1.27063134, -1.06866943,  0.64516273,
        0.18102654,  0.20687731, -0.2563266 , -0.32244676, -0.61428066,
        1.83766858, -3.065087  , -0.94214552, -0.42013033, -0.02370516,
       -0.36793715, -1.20260036, -0.21662638,  0.22498187,  0.75160348,
        0.97605559,  1.49964651, -0.46510378,  0.95254994,  0.83900215,
       -0.30549632, -0.59748397,  0.57252363, -0.23369552, -0.07588971,
       -1.51889228,  2.12139963,  0.93986458,  1.35881332,  0.81818521,
        1.76209265, -0.90403706,  0.67142255,  0.52374964, -0.03420846,
       -0.38336675, -0.70068105,  1.64257852,  0.15705458, -0.75815111,
        0.21395983, -0.49714383, -1.88709004,  0.16433392, -0.17914887,
        0.61293316, -0.08666044,  0.78237088, -0.08435752, -0.9681533 ,
        0.16894181,  0.73322653, -0.59761075, -0.11817217, -0.13

## b) x에서 값이 0.2 보다 큰 원소들을 골라내시오

In [22]:
x[x>0.2]

array([0.98130294, 0.97430864, 0.41721863, 0.5215632 , 1.35180415,
       0.57283013, 1.87046792, 1.7484412 , 1.27063134, 0.64516273,
       0.20687731, 1.83766858, 0.22498187, 0.75160348, 0.97605559,
       1.49964651, 0.95254994, 0.83900215, 0.57252363, 2.12139963,
       0.93986458, 1.35881332, 0.81818521, 1.76209265, 0.67142255,
       0.52374964, 1.64257852, 0.21395983, 0.61293316, 0.78237088,
       0.73322653, 0.91980018, 1.40134759, 0.41323504, 1.06475868,
       0.72338523, 0.47497139, 1.39450349, 0.46776579, 0.73655627,
       1.31098742, 0.679435  , 0.92365568])

# 문제 3. 선형방정식 풀기(해 구하기)

다음과 같은 방정식이 있다.
3x+6y-5z=12x-3y+2z=-25x-y+4z=10

a) 위 식을 numpy를 이용해서 Ax=B 형태로 나타내시오 (A와 B만 생성)

In [23]:
A=np.mat([[3,6,-5],[12,-3,2],[-25,-1,4]])

In [24]:
A

matrix([[  3,   6,  -5],
        [ 12,  -3,   2],
        [-25,  -1,   4]])

In [25]:
B=np.mat([[10],[10],[10]])

In [26]:
B

matrix([[10],
        [10],
        [10]])

b) A의 역행렬을 구하시오

In [27]:
lin.inv(A)

matrix([[0.05464481, 0.10382514, 0.01639344],
        [0.53551913, 0.61748634, 0.36065574],
        [0.47540984, 0.80327869, 0.44262295]])

c) 방정식의 해 벡터 x를 구하시오

In [28]:
lin.inv(A)*B

matrix([[ 1.74863388],
        [15.13661202],
        [17.21311475]])

In [29]:
lin.solve(A,B)

matrix([[ 1.74863388],
        [15.13661202],
        [17.21311475]])